# Generated by Django 3.0.9 on 2020-08-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
